In [1]:
import sys
sys.path.insert(0,'/Users/walfits/Repositories/YAMLP/SciFlow')
import CoulombMatrix as cm
import PartialCharge as pc
import ImportData as imp

In [2]:
X, y, Q = imp.loadPd_q("/Users/walfits/Repositories/trainingNN/dataSets/PBE_B3LYP/pbe_b3lyp_partQ_rel.csv")

In [3]:
PCCM = pc.PartialCharges(X, y, Q)
descriptor, y = PCCM.generatePCCM(numRep=5)

Generated the partial charge coulomb matrix (partially randomised).


In [4]:
descriptor.shape

(88755, 28)

In [5]:
print descriptor[0]

[  0.74066678   0.41791193   0.41746334   0.41793639   5.18959833
   1.23216541   1.41871522   0.74294056   0.41813204   0.41858768
   5.19751518   1.12575382   1.18505129   0.7414071    0.41815087
   5.19201506   0.97039868   1.08555554   0.74302676   5.1976879
   1.38521863   1.50730761  42.95989718   8.99198804   9.9055713
  38.30582529  37.3701958   46.38781394]


In [6]:
import numpy as np
nc = np.zeros(7)
nc.shape

(7,)

In [7]:
nc[0:4] = 1.0
nc[4:6] = 6.0
nc[6] = 7.0
print nc

[ 1.  1.  1.  1.  6.  6.  7.]


In [8]:
nc_big = np.tile(nc, (descriptor.shape[0],1))
print nc_big.shape
print nc_big[0:5]

(88755, 7)
[[ 1.  1.  1.  1.  6.  6.  7.]
 [ 1.  1.  1.  1.  6.  6.  7.]
 [ 1.  1.  1.  1.  6.  6.  7.]
 [ 1.  1.  1.  1.  6.  6.  7.]
 [ 1.  1.  1.  1.  6.  6.  7.]]


In [9]:
print descriptor.shape, nc_big.shape, np.reshape(y, (y.shape[0],1)).shape
data = np.concatenate((descriptor, nc_big, np.reshape(y, (y.shape[0],1))), axis = 1)
print data.shape

(88755, 28) (88755, 7) (88755, 1)
(88755, 36)


In [11]:
import numpy as np
np.savetxt('hyb3.csv', data, delimiter=',', newline='\n')